idf_component_register(
    SRCS
        "SensorManager.cpp"
        "Filters.cpp"
        "DataFusion.cpp"
        "DisplayManager.cpp"
        "NetworkManager.cpp"
        "StorageHelper.cpp"
        "test_bme680.cpp"
        "test_pms5003.cpp"
        "test_mq135.cpp"
        "main.cpp"
    INCLUDE_DIRS
        "include"
    REQUIRES
        esp_driver_i2c
        esp_driver_uart
        esp_driver_gpio
        esp_driver_spi
        esp_driver_sdspi
        sdmmc
        esp_adc
        esp_wifi
        esp_netif
        esp_event
        mqtt
        nvs_flash
        fatfs
        vfs
        esp_timer
        cjson
        lwip
        freertos
        hd44780
        pcf8574
        bme680      # esp-idf-lib/bme680 (driver chính cho cảm biến T/RH/P/Gas)
        i2cdev      # esp-idf-lib/i2cdev — cần cho i2cdev_init() chia sẻ bus I2C
)
